### ISSUE TITLE
io.trino.spi.TrinoException: Partition location does not exist: hdfs://mycluster/user/hive/warehouse

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/Stream-Data#10]
```bash
io.trino.spi.TrinoException: Partition location does not exist: hdfs://mycluster/user/hive/warehouse/my_table-__PLACEHOLDER__
	at io.trino.plugin.hive.fs.HiveFileIterator$FileStatusIterator.processException(HiveFileIterator.java:224)
	at io.trino.plugin.hive.fs.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:194)
	at io.trino.plugin.hive.fs.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:113)
	at io.trino.plugin.hive.fs.HiveFileIterator.<init>(HiveFileIterator.java:73)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.createInternalHiveSplitIterator(BackgroundHiveSplitLoader.java:802)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:552)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:393)
	at io.trino.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:307)
	at io.trino.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.trino.$gen.Trino_412____20230414_071402_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dyrnq** [comment]
my_table is hive external table.
