### ISSUE TITLE
org.apache.cassandra.exceptions.ConfigurationException: Saved cluster name Test Cluster != configured name

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/Stream-Data#14]
```bash
Apr 23 11:25:30 m211 sh[17638]: ERROR [main] 2023-04-23 11:25:30,401 CassandraDaemon.java:898 - Fatal exception during initialization
Apr 23 11:25:30 m211 sh[17638]: org.apache.cassandra.exceptions.ConfigurationException: Saved cluster name Test Cluster != configured name mycluster
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.db.SystemKeyspace.checkHealth(SystemKeyspace.java:1085)
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.service.StartupChecks$13.execute(StartupChecks.java:631)
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:175)
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.service.CassandraDaemon.runStartupChecks(CassandraDaemon.java:503)
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:257)
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:752)
Apr 23 11:25:30 m211 sh[17638]:         at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:876)
Apr 23 11:25:31 m211 sh[17769]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

```

**Comment by dyrnq** [comment]
```bash
rm -rf $CASSANDRA_HOME/data
```
then restart
