### ISSUE TITLE
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/Stream-Data#20]
```bash
LeaderAndEpoch{leader=Optional[192.168.6.212:9092 (id: 12 rack: null)], epoch=0}}. (org.apache.kafka.clients.consumer.internals.SubscriptionState:399)
[2023-04-25 10:14:30,248] INFO [kafka-console-sink|task-0] [Consumer clientId=connector-consumer-kafka-console-sink-0, groupId=connect-kafka-console-sink] Resetting offset for partition mytopic-1 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[192.168.6.213:9092 (id: 13 rack: null)], epoch=0}}. (org.apache.kafka.clients.consumer.internals.SubscriptionState:399)
[2023-04-25 10:14:30,256] ERROR [kafka-console-sink|task-0] WorkerSinkTask{id=kafka-console-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:230)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:518)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:335)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:330)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:88)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:518)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:180)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:214)
	... 14 more
[2023-04-25 10:14:30,262] INFO [kafka-console-sink|task-0] [Consumer clientId=connector-consumer-kafka-console-sink-0, groupId=connect-kafka-console-sink] Revoke previously assigned partitions mytopic-0, mytopic-1, mytopic-2 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:336)
[2023-04-25 10:14:30,263] INFO [kafka-console-sink|task-0] [Consumer clientId=connector-consumer-kafka-console-sink-0, groupId=connect-kafka-console-sink] Member connector-consumer-kafka-console-sink-0-72be617a-429f-43ce-b819-cd3ceeff1517 sending LeaveGroup request to coordinator 192.168.6.211:9092 (id: 2147483636 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1123)
[2023-04-25 10:14:30,264] INFO [kafka-console-sink|task-0] [Consumer clientId=connector-consumer-kafka-console-sink-0, groupId=connect-kafka-console-sink] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1015)
[2023-04-25 10:14:30,264] INFO [kafka-console-sink|task-0] [Consumer clientId=connector-consumer-kafka-console-sink-0, groupId=connect-kafka-console-sink] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1062)
[2023-04-25 10:14:30,267] INFO [kafka-console-sink|task-0] Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:693)
[2023-04-25 10:14:30,268] INFO [kafka-console-sink|task-0] Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:697)
[2023-04-25 10:14:30,268] INFO [kafka-console-sink|task-0] Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:703)
[2023-04-25 10:14:30,272] INFO [kafka-console-sink|task-0] App info kafka.consumer for connector-consumer-kafka-console-sink-0 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
Apr 25, 2023 10:14:30 AM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method listLoggers in org.apache.kafka.connect.runtime.rest.resources.LoggingResource contains empty path annotation.
WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

[2023-04-25 10:14:30,372] INFO Started o.e.j.s.ServletContextHandler@503fbbc6{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:921)
[2023-04-25 10:14:30,372] INFO REST resources initialized; server is started and ready to handle requests (org.apache.kafka.connect.runtime.rest.RestServer:309)
[2023-04-25 10:14:30,372] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:56)

```

**Comment by dyrnq** [comment]
```json
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": false,
        "value.converter.schemas.enable": false
```
