### ISSUE TITLE
Connector configuration is invalid and contains the following 1 error(s):\nThe 'topic.prefix' value is invalid: A value is required\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/Stream-Data#23]
```json
{
  "error_code": 400,
  "message": "Connector configuration is invalid and contains the following 1 error(s):\nThe 'topic.prefix' value is invalid: A value is required\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"
}

```

**Comment by dyrnq** [comment]
```bash
[2023-04-27 19:40:00,293] WARN [kafka-mysql-source|task-0] These configurations '[metrics.context.connect.kafka.cluster.id, metrics.context.connect.group.id]' were supplied but are not used yet. (org.apache.kafka.clients.producer.ProducerConfig:385)
[2023-04-27 19:40:00,294] INFO [kafka-mysql-source|task-0] Kafka version: 3.4.0 (org.apache.kafka.common.utils.AppInfoParser:119)
[2023-04-27 19:40:00,294] INFO [kafka-mysql-source|task-0] Kafka commitId: 2e1947d240607d53 (org.apache.kafka.common.utils.AppInfoParser:120)
[2023-04-27 19:40:00,294] INFO [kafka-mysql-source|task-0] Kafka startTimeMs: 1682595600294 (org.apache.kafka.common.utils.AppInfoParser:121)
[2023-04-27 19:40:00,297] INFO [kafka-mysql-source|task-0] [Producer clientId=connector-producer-kafka-mysql-source-0] Cluster ID: kVfz6b8LQEeFUtSZSt4pLQ (org.apache.kafka.clients.Metadata:287)
[2023-04-27 19:40:00,302] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1705)
[2023-04-27 19:40:00,304] INFO [kafka-mysql-source|task-0] Starting MySqlConnectorTask with configuration: (io.debezium.connector.common.BaseSourceTask:124)
[2023-04-27 19:40:00,306] INFO [kafka-mysql-source|task-0]    connector.class = io.debezium.connector.mysql.MySqlConnector (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,306] INFO [kafka-mysql-source|task-0]    database.allowPublicKeyRetrieval = true (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,306] INFO [kafka-mysql-source|task-0]    database.user = redpanda (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,306] INFO [kafka-mysql-source|task-0]    database.server.id = 1 (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,306] INFO [kafka-mysql-source|task-0]    tasks.max = 1 (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    database.history.kafka.bootstrap.servers = redpanda:9092 (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    database.history.kafka.topic = dbhistory.mysql (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    database.server.name = mysql (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    database.port = 3306 (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    include.schema.changes = true (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    table.whitelist = redpanda.payment_method (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    topic.prefix = mysql (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    task.class = io.debezium.connector.mysql.MySqlConnectorTask (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    database.hostname = 192.168.6.215 (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    database.password = ******** (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,307] INFO [kafka-mysql-source|task-0]    name = kafka-mysql-source (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,308] INFO [kafka-mysql-source|task-0]    database.include.list = redpanda (io.debezium.connector.common.BaseSourceTask:126)
[2023-04-27 19:40:00,308] INFO [kafka-mysql-source|task-0] WorkerSourceTask{id=kafka-mysql-source-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.AbstractWorkerSourceTask:275)
[2023-04-27 19:40:00,310] INFO [kafka-mysql-source|task-0] Attempting to start task (io.debezium.connector.common.BaseSourceTask:243)
[2023-04-27 19:40:00,338] INFO [kafka-mysql-source|task-0] Loading the custom topic naming strategy plugin: io.debezium.schema.DefaultTopicNamingStrategy (io.debezium.config.CommonConnectorConfig:849)
[2023-04-27 19:40:00,380] INFO [kafka-mysql-source|task-0] No previous offsets found (io.debezium.connector.common.BaseSourceTask:375)
[2023-04-27 19:40:00,442] ERROR [kafka-mysql-source|task-0] The 'schema.history.internal.kafka.topic' value is invalid: A value is required (io.debezium.storage.kafka.history.KafkaSchemaHistory:1932)
[2023-04-27 19:40:00,443] ERROR [kafka-mysql-source|task-0] The 'schema.history.internal.kafka.bootstrap.servers' value is invalid: A value is required (io.debezium.storage.kafka.history.KafkaSchemaHistory:1932)
[2023-04-27 19:40:00,444] ERROR [kafka-mysql-source|task-0] WorkerSourceTask{id=kafka-mysql-source-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
org.apache.kafka.connect.errors.ConnectException: Error configuring an instance of KafkaSchemaHistory; check the logs for details
	at io.debezium.storage.kafka.history.KafkaSchemaHistory.configure(KafkaSchemaHistory.java:208)
	at io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.getSchemaHistory(HistorizedRelationalDatabaseConnectorConfig.java:137)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:49)
	at io.debezium.connector.mysql.MySqlDatabaseSchema.<init>(MySqlDatabaseSchema.java:82)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:92)
	at io.debezium.connector.common.BaseSourceTask.startIfNeededAndPossible(BaseSourceTask.java:244)
	at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:153)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.poll(AbstractWorkerSourceTask.java:457)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:351)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-27 19:40:00,446] INFO [kafka-mysql-source|task-0] Stopping down connector (io.debezium.connector.common.BaseSourceTask:278)
[2023-04-27 19:40:00,448] INFO [kafka-mysql-source|task-0] Connection gracefully closed (io.debezium.jdbc.JdbcConnection:947)
[2023-04-27 19:40:00,449] INFO [kafka-mysql-source|task-0] [Producer clientId=connector-producer-kafka-mysql-source-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1310)
[2023-04-27 19:40:00,452] INFO [kafka-mysql-source|task-0] Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:693)
[2023-04-27 19:40:00,453] INFO [kafka-mysql-source|task-0] Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:697)
[2023-04-27 19:40:00,453] INFO [kafka-mysql-source|task-0] Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:703)
[2023-04-27 19:40:00,453] INFO [kafka-mysql-source|task-0] App info kafka.producer for connector-producer-kafka-mysql-source-0 unregistered (org.apache.kafka.common.utils.AppInfoParse
```

**Comment by dyrnq** [comment]
Add
```json
"topic.prefix": "mysql-"
```
