### ISSUE TITLE
The 'schema.history.internal.kafka.topic' value is invalid: A value is required (io.debezium.storage.kafka.history.KafkaSchemaHistory:1932)

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/Stream-Data#24]
```bash
[2023-04-27 19:43:21,841] INFO [kafka-mysql-source|task-0] Attempting to start task (io.debezium.connector.common.BaseSourceTask:243)
[2023-04-27 19:43:21,843] INFO [kafka-mysql-source|task-0] Loading the custom topic naming strategy plugin: io.debezium.schema.DefaultTopicNamingStrategy (io.debezium.config.CommonConnectorConfig:849)
[2023-04-27 19:43:21,857] INFO [kafka-mysql-source|task-0] No previous offsets found (io.debezium.connector.common.BaseSourceTask:375)
[2023-04-27 19:43:21,863] ERROR [kafka-mysql-source|task-0] The 'schema.history.internal.kafka.topic' value is invalid: A value is required (io.debezium.storage.kafka.history.KafkaSchemaHistory:1932)
[2023-04-27 19:43:21,863] ERROR [kafka-mysql-source|task-0] The 'schema.history.internal.kafka.bootstrap.servers' value is invalid: A value is required (io.debezium.storage.kafka.history.KafkaSchemaHistory:1932)
[2023-04-27 19:43:21,864] ERROR [kafka-mysql-source|task-0] WorkerSourceTask{id=kafka-mysql-source-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:210)
org.apache.kafka.connect.errors.ConnectException: Error configuring an instance of KafkaSchemaHistory; check the logs for details
	at io.debezium.storage.kafka.history.KafkaSchemaHistory.configure(KafkaSchemaHistory.java:208)
	at io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.getSchemaHistory(HistorizedRelationalDatabaseConnectorConfig.java:137)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:49)
	at io.debezium.connector.mysql.MySqlDatabaseSchema.<init>(MySqlDatabaseSchema.java:82)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:92)
	at io.debezium.connector.common.BaseSourceTask.startIfNeededAndPossible(BaseSourceTask.java:244)
	at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:153)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.poll(AbstractWorkerSourceTask.java:457)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:351)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-04-27 19:43:21,864] INFO [kafka-mysql-source|task-0] Stopping down connector (io.debezium.connector.common.BaseSourceTask:278)
[2023-04-27 19:43:21,866] INFO [kafka-mysql-source|task-0] Connection gracefully closed (io.debezium.jdbc.JdbcConnection:947)
[2023-04-27 19:43:21,866] INFO [kafka-mysql-source|task-0] [Producer clientId=connector-producer-kafka-mysql-source-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:1310)
[2023-04-27 19:43:21,868] INFO [kafka-mysql-source|task-0] Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:693)
[2023-04-27 19:43:21,868] INFO [kafka-mysql-source|task-0] Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:697)
[2023-04-27 19:43:21,868] INFO [kafka-mysql-source|task-0] Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:703)
[2023-04-27 19:43:21,868] INFO [kafka-mysql-source|task-0] App info kafka.producer for connector-producer-kafka-mysql-source-0 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)

```

**Comment by dyrnq** [comment]
ADD
```json
        "schema.history.internal.kafka.bootstrap.servers": "localhost:9092",
        "schema.history.internal.kafka.topic": "schema-changes.inventory"
```
